### ISSUE TITLE
Clarify warnings from run_time.ini file errors

### ISSUE THREAD

**Issue by toddgraham121** [ElectionDataAnalysis/electiondata#719]
After updating from version 1.0 to 2.0, the `run_time.ini` file title changed from `[election-data-analysis]` to `[electiondata]`. The error message should specify the issue. Currently the short test summary info is as follows: 

```
dataloading_tests/test_dataloading.py:60: AttributeError
======================================================== short test summary info ========================================================
FAILED dataloading_tests/test_dataloading.py::test_dataloader_exists - AssertionError: Specify viable dataloader parameter file path w...
FAILED dataloading_tests/test_dataloading.py::test_loading - AttributeError: 'NoneType' object has no attribute 'get_testing_data'
FAILED dataloading_tests/test_dataloading.py::test_multielection_loading - AttributeError: 'NoneType' object has no attribute 'd'
ERROR dataloading_tests/test_dataloading.py::test_multielection_loading - AttributeError: 'NoneType' object has no attribute 'close_an...
```

**Comment by sfsinger19103** [comment]
I'm not sure how to fix this, since the obscurity is partly because of how pytest reports error messages. Presumably if you looked at the pytest information preceding the "short test summary info" you'd see the whole error message about specifying a viable parameter path.
